# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b97411b8bedd0b92d94570b0b93e323457199193da1b5ae7c1f5d39739e10f4c5750ec7e771bddf9a102cc5fb7ac310e18da87575b02435641313321d1d5d31c

test:
  secret_key_base: e742d2c5de57a7a65ba4d9b60d193cdfbc2e4ea06834a567b9d4a2b15f6fa488963793476b3abaac7805de3483442f199a17900e524e446a84a5eaaa4003ac2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
